### ISSUE TITLE
mr-dep-walk throws when module not found

### ISSUE THREAD

**Issue by rwjblue** [ember-engines/broccoli-dependency-funnel#20]
The previous implementation (via rollup) would mark the unfound module as an "external dependency" and keep going.

/cc @stefanpenner

**Comment by stefanpenner** [comment]
> would mark the unfound module as an "external dependency" and keep going.

Does that mean it just doesn't traverse once it hits a missing file? e.g. no visibility beyond that point?

Do we not need to explicitly mark them as external?

**Comment by stefanpenner** [comment]
@rwjblue i'll gladly address, just need answers to ^
