### ISSUE TITLE
Actually use heimdall

### ISSUE THREAD

**Issue by trentmwillis** [ember-engines/broccoli-dependency-funnel#9]
Currently heimdall and heimdall-logger are installed, but unused. We should specify what we want to track and implement it accordingly.

**Comment by rwjblue** [comment]
I'd suggest tracking:

* Build called
* [entry point not found](https://github.com/ember-engines/broccoli-dependency-funnel/blob/master/src/index.js#L77)
* Invalidation due to
  * entry point change
  * something imported by entry point changed
  * included files changed
